### ISSUE TITLE
Does not handle undefined values for keys in an object

### ISSUE THREAD

**Issue by AddictArts** [cvadillo/js-object-pretty-print#2]
Example:
```javascript
{ key: undefined }
```

**Comment by AddictArts** [comment]
It appears the fix could be as simple as, 
https://github.com/cvadillo/js-object-pretty-print/blob/master/index.js#L131
```javascript
return fromArray + (element !== undefined) element.toString() : '';
```
or something like that in the pretty function

**Comment by cvadillo** [comment]
Thank you @AddictArts, I am working on this bug. Expect a solution soon

**Comment by cvadillo** [comment]
Bug is fixed
